var tek = require('tek'),
    file = tek.file,
    fs = require('fs'),
    path = require('path'),
    resolve = path.resolve,
    config = require('../app.config'),
    JobQueue = tek.meta['JobQueue'];

function handleErr(err) {
    console.error(err);
}

/**
 * publish js file
 */
exports = module.exports = function (filepath, namespace, data, callback) {
    try {
        var declares = exports.namespaceDeclareLines(namespace);
        var content = [
            "/** auto generated by u.publish.js **/\n",
            (declares.length ? (declares.join("\n") + "\n") : ''),
            [namespace, '=', ''].join(' '),
            JSON.stringify(data, null, 4),
            [';'].join(' ')
        ].join('');

        fs.writeFile(filepath, content, function (err) {
            err && handleErr(err);
            callback && callback(!err && filepath);
        });
    } catch (e) {
        handleErr(e);
    }
};

/**
 * create namespace declare strings
 * @param namespace
 */
exports.namespaceDeclareLines = function (namespace) {
    var current = null;
    var names = namespace.split('.');
    names.pop();
    return names.map(function (name) {
        current = current ? [current, name].join('.') : name;
        return "if (typeof(" + current + ") === 'undefined') " + current + " = {};";
    });
};